/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as AsnsRouteImport } from './routes/asns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders_.$orderId'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as AsnsAsnIdRouteImport } from './routes/asns_.$asnId'
import { Route as ApiSuggestBarcodeRouteImport } from './routes/api/suggest-barcode'
import { Route as ApiPickProductImageRouteImport } from './routes/api/pick-product-image'
import { Route as ApiMintsoftRouteImport } from './routes/api/mintsoft'
import { Route as ApiGoogleImageRouteImport } from './routes/api/google-image'
import { Route as ApiEstimateWeightRouteImport } from './routes/api/estimate-weight'
import { Route as ApiAmazonImageRouteImport } from './routes/api/amazon-image'
import { Route as DRouteImport } from './routes/d.'
import { Route as ApiPublicDSlugRouteImport } from './routes/api/public/d/$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const AsnsRoute = AsnsRouteImport.update({
  id: '/asns',
  path: '/asns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AsnsAsnIdRoute = AsnsAsnIdRouteImport.update({
  id: '/asns_/$asnId',
  path: '/asns/$asnId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestBarcodeRoute = ApiSuggestBarcodeRouteImport.update({
  id: '/api/suggest-barcode',
  path: '/api/suggest-barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPickProductImageRoute = ApiPickProductImageRouteImport.update({
  id: '/api/pick-product-image',
  path: '/api/pick-product-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMintsoftRoute = ApiMintsoftRouteImport.update({
  id: '/api/mintsoft',
  path: '/api/mintsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleImageRoute = ApiGoogleImageRouteImport.update({
  id: '/api/google-image',
  path: '/api/google-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstimateWeightRoute = ApiEstimateWeightRouteImport.update({
  id: '/api/estimate-weight',
  path: '/api/estimate-weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAmazonImageRoute = ApiAmazonImageRouteImport.update({
  id: '/api/amazon-image',
  path: '/api/amazon-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DRoute = DRouteImport.update({
  id: '/d/',
  path: '/d/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDSlugRoute = ApiPublicDSlugRouteImport.update({
  id: '/api/public/d/$slug',
  path: '/api/public/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asns': typeof AsnsRoute
  '/development': typeof DevelopmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/d/': typeof DRoute
  '/api/amazon-image': typeof ApiAmazonImageRoute
  '/api/estimate-weight': typeof ApiEstimateWeightRoute
  '/api/google-image': typeof ApiGoogleImageRoute
  '/api/mintsoft': typeof ApiMintsoftRoute
  '/api/pick-product-image': typeof ApiPickProductImageRoute
  '/api/suggest-barcode': typeof ApiSuggestBarcodeRoute
  '/asns/$asnId': typeof AsnsAsnIdRoute
  '/d/$slug': typeof DSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/public/d/$slug': typeof ApiPublicDSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asns': typeof AsnsRoute
  '/development': typeof DevelopmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/d': typeof DRoute
  '/api/amazon-image': typeof ApiAmazonImageRoute
  '/api/estimate-weight': typeof ApiEstimateWeightRoute
  '/api/google-image': typeof ApiGoogleImageRoute
  '/api/mintsoft': typeof ApiMintsoftRoute
  '/api/pick-product-image': typeof ApiPickProductImageRoute
  '/api/suggest-barcode': typeof ApiSuggestBarcodeRoute
  '/asns/$asnId': typeof AsnsAsnIdRoute
  '/d/$slug': typeof DSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/api/public/d/$slug': typeof ApiPublicDSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asns': typeof AsnsRoute
  '/development': typeof DevelopmentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/d/': typeof DRoute
  '/api/amazon-image': typeof ApiAmazonImageRoute
  '/api/estimate-weight': typeof ApiEstimateWeightRoute
  '/api/google-image': typeof ApiGoogleImageRoute
  '/api/mintsoft': typeof ApiMintsoftRoute
  '/api/pick-product-image': typeof ApiPickProductImageRoute
  '/api/suggest-barcode': typeof ApiSuggestBarcodeRoute
  '/asns_/$asnId': typeof AsnsAsnIdRoute
  '/d/$slug': typeof DSlugRoute
  '/orders_/$orderId': typeof OrdersOrderIdRoute
  '/api/public/d/$slug': typeof ApiPublicDSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asns'
    | '/development'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/d/'
    | '/api/amazon-image'
    | '/api/estimate-weight'
    | '/api/google-image'
    | '/api/mintsoft'
    | '/api/pick-product-image'
    | '/api/suggest-barcode'
    | '/asns/$asnId'
    | '/d/$slug'
    | '/orders/$orderId'
    | '/api/public/d/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asns'
    | '/development'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/d'
    | '/api/amazon-image'
    | '/api/estimate-weight'
    | '/api/google-image'
    | '/api/mintsoft'
    | '/api/pick-product-image'
    | '/api/suggest-barcode'
    | '/asns/$asnId'
    | '/d/$slug'
    | '/orders/$orderId'
    | '/api/public/d/$slug'
  id:
    | '__root__'
    | '/'
    | '/asns'
    | '/development'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/d/'
    | '/api/amazon-image'
    | '/api/estimate-weight'
    | '/api/google-image'
    | '/api/mintsoft'
    | '/api/pick-product-image'
    | '/api/suggest-barcode'
    | '/asns_/$asnId'
    | '/d/$slug'
    | '/orders_/$orderId'
    | '/api/public/d/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsnsRoute: typeof AsnsRoute
  DevelopmentRoute: typeof DevelopmentRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  DRoute: typeof DRoute
  ApiAmazonImageRoute: typeof ApiAmazonImageRoute
  ApiEstimateWeightRoute: typeof ApiEstimateWeightRoute
  ApiGoogleImageRoute: typeof ApiGoogleImageRoute
  ApiMintsoftRoute: typeof ApiMintsoftRoute
  ApiPickProductImageRoute: typeof ApiPickProductImageRoute
  ApiSuggestBarcodeRoute: typeof ApiSuggestBarcodeRoute
  AsnsAsnIdRoute: typeof AsnsAsnIdRoute
  DSlugRoute: typeof DSlugRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ApiPublicDSlugRoute: typeof ApiPublicDSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asns': {
      id: '/asns'
      path: '/asns'
      fullPath: '/asns'
      preLoaderRoute: typeof AsnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$orderId': {
      id: '/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asns_/$asnId': {
      id: '/asns_/$asnId'
      path: '/asns/$asnId'
      fullPath: '/asns/$asnId'
      preLoaderRoute: typeof AsnsAsnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-barcode': {
      id: '/api/suggest-barcode'
      path: '/api/suggest-barcode'
      fullPath: '/api/suggest-barcode'
      preLoaderRoute: typeof ApiSuggestBarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pick-product-image': {
      id: '/api/pick-product-image'
      path: '/api/pick-product-image'
      fullPath: '/api/pick-product-image'
      preLoaderRoute: typeof ApiPickProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mintsoft': {
      id: '/api/mintsoft'
      path: '/api/mintsoft'
      fullPath: '/api/mintsoft'
      preLoaderRoute: typeof ApiMintsoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-image': {
      id: '/api/google-image'
      path: '/api/google-image'
      fullPath: '/api/google-image'
      preLoaderRoute: typeof ApiGoogleImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/estimate-weight': {
      id: '/api/estimate-weight'
      path: '/api/estimate-weight'
      fullPath: '/api/estimate-weight'
      preLoaderRoute: typeof ApiEstimateWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/amazon-image': {
      id: '/api/amazon-image'
      path: '/api/amazon-image'
      fullPath: '/api/amazon-image'
      preLoaderRoute: typeof ApiAmazonImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/': {
      id: '/d/'
      path: '/d'
      fullPath: '/d/'
      preLoaderRoute: typeof DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/d/$slug': {
      id: '/api/public/d/$slug'
      path: '/api/public/d/$slug'
      fullPath: '/api/public/d/$slug'
      preLoaderRoute: typeof ApiPublicDSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsnsRoute: AsnsRoute,
  DevelopmentRoute: DevelopmentRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  DRoute: DRoute,
  ApiAmazonImageRoute: ApiAmazonImageRoute,
  ApiEstimateWeightRoute: ApiEstimateWeightRoute,
  ApiGoogleImageRoute: ApiGoogleImageRoute,
  ApiMintsoftRoute: ApiMintsoftRoute,
  ApiPickProductImageRoute: ApiPickProductImageRoute,
  ApiSuggestBarcodeRoute: ApiSuggestBarcodeRoute,
  AsnsAsnIdRoute: AsnsAsnIdRoute,
  DSlugRoute: DSlugRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ApiPublicDSlugRoute: ApiPublicDSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
