/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MobileEmulatorRouteImport } from './routes/mobile-emulator'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoiceMergerRouteImport } from './routes/invoice-merger'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FbaCalculatorRouteImport } from './routes/fba-calculator'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as AsnsRouteImport } from './routes/asns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileIndexRouteImport } from './routes/mobile.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders_.$orderId'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as AsnsAsnIdRouteImport } from './routes/asns_.$asnId'
import { Route as ApiSuggestBarcodeRouteImport } from './routes/api/suggest-barcode'
import { Route as ApiPickProductImageRouteImport } from './routes/api/pick-product-image'
import { Route as ApiMintsoftRouteImport } from './routes/api/mintsoft'
import { Route as ApiGoogleImageRouteImport } from './routes/api/google-image'
import { Route as ApiEstimateWeightRouteImport } from './routes/api/estimate-weight'
import { Route as ApiAmazonImageRouteImport } from './routes/api/amazon-image'
import { Route as DRouteImport } from './routes/d.'
import { Route as MobileStockAsnsRouteImport } from './routes/mobile.stock.asns'
import { Route as AsnsAsnIdQuickRouteImport } from './routes/asns_.$asnId.quick'
import { Route as ApiPublicSetupWarningLabelsBucketRouteImport } from './routes/api/public/setup-warning-labels-bucket'
import { Route as ApiPublicSetupDesktopBucketRouteImport } from './routes/api/public/setup-desktop-bucket'
import { Route as ApiPublicDSlugRouteImport } from './routes/api/public/d/$slug'
import { Route as ApiPublicCronSyncMintsoftRouteImport } from './routes/api/public/cron/sync-mintsoft'

const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileEmulatorRoute = MobileEmulatorRouteImport.update({
  id: '/mobile-emulator',
  path: '/mobile-emulator',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceMergerRoute = InvoiceMergerRouteImport.update({
  id: '/invoice-merger',
  path: '/invoice-merger',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FbaCalculatorRoute = FbaCalculatorRouteImport.update({
  id: '/fba-calculator',
  path: '/fba-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const AsnsRoute = AsnsRouteImport.update({
  id: '/asns',
  path: '/asns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AsnsAsnIdRoute = AsnsAsnIdRouteImport.update({
  id: '/asns_/$asnId',
  path: '/asns/$asnId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestBarcodeRoute = ApiSuggestBarcodeRouteImport.update({
  id: '/api/suggest-barcode',
  path: '/api/suggest-barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPickProductImageRoute = ApiPickProductImageRouteImport.update({
  id: '/api/pick-product-image',
  path: '/api/pick-product-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMintsoftRoute = ApiMintsoftRouteImport.update({
  id: '/api/mintsoft',
  path: '/api/mintsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleImageRoute = ApiGoogleImageRouteImport.update({
  id: '/api/google-image',
  path: '/api/google-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstimateWeightRoute = ApiEstimateWeightRouteImport.update({
  id: '/api/estimate-weight',
  path: '/api/estimate-weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAmazonImageRoute = ApiAmazonImageRouteImport.update({
  id: '/api/amazon-image',
  path: '/api/amazon-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DRoute = DRouteImport.update({
  id: '/d/',
  path: '/d/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileStockAsnsRoute = MobileStockAsnsRouteImport.update({
  id: '/stock/asns',
  path: '/stock/asns',
  getParentRoute: () => MobileRoute,
} as any)
const AsnsAsnIdQuickRoute = AsnsAsnIdQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => AsnsAsnIdRoute,
} as any)
const ApiPublicSetupWarningLabelsBucketRoute =
  ApiPublicSetupWarningLabelsBucketRouteImport.update({
    id: '/api/public/setup-warning-labels-bucket',
    path: '/api/public/setup-warning-labels-bucket',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSetupDesktopBucketRoute =
  ApiPublicSetupDesktopBucketRouteImport.update({
    id: '/api/public/setup-desktop-bucket',
    path: '/api/public/setup-desktop-bucket',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDSlugRoute = ApiPublicDSlugRouteImport.update({
  id: '/api/public/d/$slug',
  path: '/api/public/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSyncMintsoftRoute =
  ApiPublicCronSyncMintsoftRouteImport.update({
    id: '/api/public/cron/sync-mintsoft',
    path: '/api/public/cron/sync-mintsoft',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asns': typeof AsnsRoute
  '/development': typeof DevelopmentRoute
  '/fba-calculator': typeof FbaCalculatorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoice-merger': typeof InvoiceMergerRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/mobile': typeof MobileRouteWithChildren
  '/mobile-emulator': typeof MobileEmulatorRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stock': typeof StockRoute
  '/d/': typeof DRoute
  '/api/amazon-image': typeof ApiAmazonImageRoute
  '/api/estimate-weight': typeof ApiEstimateWeightRoute
  '/api/google-image': typeof ApiGoogleImageRoute
  '/api/mintsoft': typeof ApiMintsoftRoute
  '/api/pick-product-image': typeof ApiPickProductImageRoute
  '/api/suggest-barcode': typeof ApiSuggestBarcodeRoute
  '/asns/$asnId': typeof AsnsAsnIdRouteWithChildren
  '/d/$slug': typeof DSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/mobile/': typeof MobileIndexRoute
  '/api/public/setup-desktop-bucket': typeof ApiPublicSetupDesktopBucketRoute
  '/api/public/setup-warning-labels-bucket': typeof ApiPublicSetupWarningLabelsBucketRoute
  '/asns/$asnId/quick': typeof AsnsAsnIdQuickRoute
  '/mobile/stock/asns': typeof MobileStockAsnsRoute
  '/api/public/cron/sync-mintsoft': typeof ApiPublicCronSyncMintsoftRoute
  '/api/public/d/$slug': typeof ApiPublicDSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asns': typeof AsnsRoute
  '/development': typeof DevelopmentRoute
  '/fba-calculator': typeof FbaCalculatorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoice-merger': typeof InvoiceMergerRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/mobile-emulator': typeof MobileEmulatorRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stock': typeof StockRoute
  '/d': typeof DRoute
  '/api/amazon-image': typeof ApiAmazonImageRoute
  '/api/estimate-weight': typeof ApiEstimateWeightRoute
  '/api/google-image': typeof ApiGoogleImageRoute
  '/api/mintsoft': typeof ApiMintsoftRoute
  '/api/pick-product-image': typeof ApiPickProductImageRoute
  '/api/suggest-barcode': typeof ApiSuggestBarcodeRoute
  '/asns/$asnId': typeof AsnsAsnIdRouteWithChildren
  '/d/$slug': typeof DSlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/mobile': typeof MobileIndexRoute
  '/api/public/setup-desktop-bucket': typeof ApiPublicSetupDesktopBucketRoute
  '/api/public/setup-warning-labels-bucket': typeof ApiPublicSetupWarningLabelsBucketRoute
  '/asns/$asnId/quick': typeof AsnsAsnIdQuickRoute
  '/mobile/stock/asns': typeof MobileStockAsnsRoute
  '/api/public/cron/sync-mintsoft': typeof ApiPublicCronSyncMintsoftRoute
  '/api/public/d/$slug': typeof ApiPublicDSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asns': typeof AsnsRoute
  '/development': typeof DevelopmentRoute
  '/fba-calculator': typeof FbaCalculatorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoice-merger': typeof InvoiceMergerRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/mobile': typeof MobileRouteWithChildren
  '/mobile-emulator': typeof MobileEmulatorRoute
  '/orders': typeof OrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stock': typeof StockRoute
  '/d/': typeof DRoute
  '/api/amazon-image': typeof ApiAmazonImageRoute
  '/api/estimate-weight': typeof ApiEstimateWeightRoute
  '/api/google-image': typeof ApiGoogleImageRoute
  '/api/mintsoft': typeof ApiMintsoftRoute
  '/api/pick-product-image': typeof ApiPickProductImageRoute
  '/api/suggest-barcode': typeof ApiSuggestBarcodeRoute
  '/asns_/$asnId': typeof AsnsAsnIdRouteWithChildren
  '/d/$slug': typeof DSlugRoute
  '/orders_/$orderId': typeof OrdersOrderIdRoute
  '/mobile/': typeof MobileIndexRoute
  '/api/public/setup-desktop-bucket': typeof ApiPublicSetupDesktopBucketRoute
  '/api/public/setup-warning-labels-bucket': typeof ApiPublicSetupWarningLabelsBucketRoute
  '/asns_/$asnId/quick': typeof AsnsAsnIdQuickRoute
  '/mobile/stock/asns': typeof MobileStockAsnsRoute
  '/api/public/cron/sync-mintsoft': typeof ApiPublicCronSyncMintsoftRoute
  '/api/public/d/$slug': typeof ApiPublicDSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asns'
    | '/development'
    | '/fba-calculator'
    | '/forgot-password'
    | '/invoice-merger'
    | '/login'
    | '/mfa'
    | '/mobile'
    | '/mobile-emulator'
    | '/orders'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stock'
    | '/d/'
    | '/api/amazon-image'
    | '/api/estimate-weight'
    | '/api/google-image'
    | '/api/mintsoft'
    | '/api/pick-product-image'
    | '/api/suggest-barcode'
    | '/asns/$asnId'
    | '/d/$slug'
    | '/orders/$orderId'
    | '/mobile/'
    | '/api/public/setup-desktop-bucket'
    | '/api/public/setup-warning-labels-bucket'
    | '/asns/$asnId/quick'
    | '/mobile/stock/asns'
    | '/api/public/cron/sync-mintsoft'
    | '/api/public/d/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asns'
    | '/development'
    | '/fba-calculator'
    | '/forgot-password'
    | '/invoice-merger'
    | '/login'
    | '/mfa'
    | '/mobile-emulator'
    | '/orders'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stock'
    | '/d'
    | '/api/amazon-image'
    | '/api/estimate-weight'
    | '/api/google-image'
    | '/api/mintsoft'
    | '/api/pick-product-image'
    | '/api/suggest-barcode'
    | '/asns/$asnId'
    | '/d/$slug'
    | '/orders/$orderId'
    | '/mobile'
    | '/api/public/setup-desktop-bucket'
    | '/api/public/setup-warning-labels-bucket'
    | '/asns/$asnId/quick'
    | '/mobile/stock/asns'
    | '/api/public/cron/sync-mintsoft'
    | '/api/public/d/$slug'
  id:
    | '__root__'
    | '/'
    | '/asns'
    | '/development'
    | '/fba-calculator'
    | '/forgot-password'
    | '/invoice-merger'
    | '/login'
    | '/mfa'
    | '/mobile'
    | '/mobile-emulator'
    | '/orders'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/stock'
    | '/d/'
    | '/api/amazon-image'
    | '/api/estimate-weight'
    | '/api/google-image'
    | '/api/mintsoft'
    | '/api/pick-product-image'
    | '/api/suggest-barcode'
    | '/asns_/$asnId'
    | '/d/$slug'
    | '/orders_/$orderId'
    | '/mobile/'
    | '/api/public/setup-desktop-bucket'
    | '/api/public/setup-warning-labels-bucket'
    | '/asns_/$asnId/quick'
    | '/mobile/stock/asns'
    | '/api/public/cron/sync-mintsoft'
    | '/api/public/d/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsnsRoute: typeof AsnsRoute
  DevelopmentRoute: typeof DevelopmentRoute
  FbaCalculatorRoute: typeof FbaCalculatorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvoiceMergerRoute: typeof InvoiceMergerRoute
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  MobileRoute: typeof MobileRouteWithChildren
  MobileEmulatorRoute: typeof MobileEmulatorRoute
  OrdersRoute: typeof OrdersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StockRoute: typeof StockRoute
  DRoute: typeof DRoute
  ApiAmazonImageRoute: typeof ApiAmazonImageRoute
  ApiEstimateWeightRoute: typeof ApiEstimateWeightRoute
  ApiGoogleImageRoute: typeof ApiGoogleImageRoute
  ApiMintsoftRoute: typeof ApiMintsoftRoute
  ApiPickProductImageRoute: typeof ApiPickProductImageRoute
  ApiSuggestBarcodeRoute: typeof ApiSuggestBarcodeRoute
  AsnsAsnIdRoute: typeof AsnsAsnIdRouteWithChildren
  DSlugRoute: typeof DSlugRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ApiPublicSetupDesktopBucketRoute: typeof ApiPublicSetupDesktopBucketRoute
  ApiPublicSetupWarningLabelsBucketRoute: typeof ApiPublicSetupWarningLabelsBucketRoute
  ApiPublicCronSyncMintsoftRoute: typeof ApiPublicCronSyncMintsoftRoute
  ApiPublicDSlugRoute: typeof ApiPublicDSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-emulator': {
      id: '/mobile-emulator'
      path: '/mobile-emulator'
      fullPath: '/mobile-emulator'
      preLoaderRoute: typeof MobileEmulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-merger': {
      id: '/invoice-merger'
      path: '/invoice-merger'
      fullPath: '/invoice-merger'
      preLoaderRoute: typeof InvoiceMergerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fba-calculator': {
      id: '/fba-calculator'
      path: '/fba-calculator'
      fullPath: '/fba-calculator'
      preLoaderRoute: typeof FbaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asns': {
      id: '/asns'
      path: '/asns'
      fullPath: '/asns'
      preLoaderRoute: typeof AsnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/orders_/$orderId': {
      id: '/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asns_/$asnId': {
      id: '/asns_/$asnId'
      path: '/asns/$asnId'
      fullPath: '/asns/$asnId'
      preLoaderRoute: typeof AsnsAsnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-barcode': {
      id: '/api/suggest-barcode'
      path: '/api/suggest-barcode'
      fullPath: '/api/suggest-barcode'
      preLoaderRoute: typeof ApiSuggestBarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pick-product-image': {
      id: '/api/pick-product-image'
      path: '/api/pick-product-image'
      fullPath: '/api/pick-product-image'
      preLoaderRoute: typeof ApiPickProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mintsoft': {
      id: '/api/mintsoft'
      path: '/api/mintsoft'
      fullPath: '/api/mintsoft'
      preLoaderRoute: typeof ApiMintsoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-image': {
      id: '/api/google-image'
      path: '/api/google-image'
      fullPath: '/api/google-image'
      preLoaderRoute: typeof ApiGoogleImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/estimate-weight': {
      id: '/api/estimate-weight'
      path: '/api/estimate-weight'
      fullPath: '/api/estimate-weight'
      preLoaderRoute: typeof ApiEstimateWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/amazon-image': {
      id: '/api/amazon-image'
      path: '/api/amazon-image'
      fullPath: '/api/amazon-image'
      preLoaderRoute: typeof ApiAmazonImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/': {
      id: '/d/'
      path: '/d'
      fullPath: '/d/'
      preLoaderRoute: typeof DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/stock/asns': {
      id: '/mobile/stock/asns'
      path: '/stock/asns'
      fullPath: '/mobile/stock/asns'
      preLoaderRoute: typeof MobileStockAsnsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/asns_/$asnId/quick': {
      id: '/asns_/$asnId/quick'
      path: '/quick'
      fullPath: '/asns/$asnId/quick'
      preLoaderRoute: typeof AsnsAsnIdQuickRouteImport
      parentRoute: typeof AsnsAsnIdRoute
    }
    '/api/public/setup-warning-labels-bucket': {
      id: '/api/public/setup-warning-labels-bucket'
      path: '/api/public/setup-warning-labels-bucket'
      fullPath: '/api/public/setup-warning-labels-bucket'
      preLoaderRoute: typeof ApiPublicSetupWarningLabelsBucketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-desktop-bucket': {
      id: '/api/public/setup-desktop-bucket'
      path: '/api/public/setup-desktop-bucket'
      fullPath: '/api/public/setup-desktop-bucket'
      preLoaderRoute: typeof ApiPublicSetupDesktopBucketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/d/$slug': {
      id: '/api/public/d/$slug'
      path: '/api/public/d/$slug'
      fullPath: '/api/public/d/$slug'
      preLoaderRoute: typeof ApiPublicDSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-mintsoft': {
      id: '/api/public/cron/sync-mintsoft'
      path: '/api/public/cron/sync-mintsoft'
      fullPath: '/api/public/cron/sync-mintsoft'
      preLoaderRoute: typeof ApiPublicCronSyncMintsoftRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MobileRouteChildren {
  MobileIndexRoute: typeof MobileIndexRoute
  MobileStockAsnsRoute: typeof MobileStockAsnsRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileIndexRoute: MobileIndexRoute,
  MobileStockAsnsRoute: MobileStockAsnsRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

interface AsnsAsnIdRouteChildren {
  AsnsAsnIdQuickRoute: typeof AsnsAsnIdQuickRoute
}

const AsnsAsnIdRouteChildren: AsnsAsnIdRouteChildren = {
  AsnsAsnIdQuickRoute: AsnsAsnIdQuickRoute,
}

const AsnsAsnIdRouteWithChildren = AsnsAsnIdRoute._addFileChildren(
  AsnsAsnIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsnsRoute: AsnsRoute,
  DevelopmentRoute: DevelopmentRoute,
  FbaCalculatorRoute: FbaCalculatorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvoiceMergerRoute: InvoiceMergerRoute,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  MobileRoute: MobileRouteWithChildren,
  MobileEmulatorRoute: MobileEmulatorRoute,
  OrdersRoute: OrdersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StockRoute: StockRoute,
  DRoute: DRoute,
  ApiAmazonImageRoute: ApiAmazonImageRoute,
  ApiEstimateWeightRoute: ApiEstimateWeightRoute,
  ApiGoogleImageRoute: ApiGoogleImageRoute,
  ApiMintsoftRoute: ApiMintsoftRoute,
  ApiPickProductImageRoute: ApiPickProductImageRoute,
  ApiSuggestBarcodeRoute: ApiSuggestBarcodeRoute,
  AsnsAsnIdRoute: AsnsAsnIdRouteWithChildren,
  DSlugRoute: DSlugRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ApiPublicSetupDesktopBucketRoute: ApiPublicSetupDesktopBucketRoute,
  ApiPublicSetupWarningLabelsBucketRoute:
    ApiPublicSetupWarningLabelsBucketRoute,
  ApiPublicCronSyncMintsoftRoute: ApiPublicCronSyncMintsoftRoute,
  ApiPublicDSlugRoute: ApiPublicDSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
